"""Add user_id column to currency

Revision ID: a5f4d1f1fc9f
Revises: 
Create Date: 2026-03-28 15:24:45.751087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f4d1f1fc9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('currency_used_id_fkey'), 'currency', type_='foreignkey')
    op.create_foreign_key(None, 'currency', 'users', ['user_id'], ['id'])
    op.drop_column('currency', 'used_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('used_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.create_foreign_key(op.f('currency_used_id_fkey'), 'currency', 'users', ['used_id'], ['id'])
    op.drop_column('currency', 'user_id')
    # ### end Alembic commands ###
